all:
	cp *.swift ../DeepLearningKitForiOS/DeepLearningKitForiOS/
	cp *.metal ../DeepLearningKitForiOS/DeepLearningKitForiOS/

	cp *.swift ../DeepLearningKitFortvOS/DeepLearningKitFortvOS/
	cp *.metal ../DeepLearningKitFortvOS/DeepLearningKitFortvOS/

	cp *.swift ../DeepLearningKitForOSX/DeepLearningKitForOSX/
	cp *.metal ../DeepLearningKitForOSX/DeepLearningKitForOSX/


